#Only work for cloud enviroment like gcp, aws, azure...
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    app: myapp #Labesl from pods
    type: front-end #Labesl from pods